version: '3.4'

services:
  algorithmservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  jiraschedulingconnectappservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

