version: '3.4'

services:
  algorithmservice:
    image: pham2604/5niubi_algo_service:${BACKEND_IMAGE_TAG}
    networks:
      - internal-network

  jiraschedulingconnectappservice:
    image: pham2604/5niubi_backend:${ALGO_IMAGE_TAG}
  
    ports:
      - "5126:80"
      - "8443:80"
      - "80:80"
    networks:
      - internal-network

  admin_webapp:
    image: pham2604/admin_webapp:${WEBAPP_IMAGE_TAG}
    ports:
      - "8080:80"
      - "2096:80"

networks:
  internal-network:
    driver: bridge


    