version: '3.4'

services:
  algorithmservice:
    image: ${DOCKER_REGISTRY-}algorithmservice
    build:
      context: .
      dockerfile: AlgorithmService/Dockerfile

  jiraschedulingconnectappservice:
    image: ${DOCKER_REGISTRY-}jiraschedulingconnectappservice
    build:
      context: .
      dockerfile: JiraSchedulingConnectAppService/Dockerfile
