name: CICD Services Workflow
on:

  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]
jobs:
  build-algo-service:
    name: Build API Algorithm Service
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}
        username: _json_key
        password: ${{ secrets.GOOGLE_CREDENTIALS }}
      
    - name: Build and push
      uses: docker/build-push-action@v4
      env:
        CLOUD_ARTIFACT_REPO: "wotaas"
        IMAGE_VERSION: dev-latest
      with:
        context: .
        file: "AlgorithmService/Dockerfile"
        push: true
        tags:  ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/${{ env.GOOGLE_CLOUD_PROJECT }}/${{ env.CLOUD_ARTIFACT_REPO }}/${{ vars.ALGO_SERVICE_IMAGE }}:${{ github.sha }}, ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/${{ env.GOOGLE_CLOUD_PROJECT }}/${{ env.CLOUD_ARTIFACT_REPO }}/${{ vars.ALGO_SERVICE_IMAGE }}:${{env.IMAGE_VERSION}}
        labels: ${{ steps.meta.outputs.labels }}

  

  deploy-algo-service:
    name: Deploy Algorithm serivce to Cloud run
    runs-on: ubuntu-latest
    needs: [
      build-algo-service
      ]
    steps:
    - uses: 'actions/checkout@v3'
    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Deploy to Cloud run
      run: gcloud run services replace .cloudrun/ortool-algo-service.yml

  automated-api-tests:
    name:  API Algorithm Service Testing
    runs-on: ubuntu-latest
    needs: [
      deploy-algo-service
      ]

    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests in Staging ENV
        run: |
          postman collection run 22303980-e10b19fb-a5b1-4d57-83b2-e5ea2392ad6f -e 28333090-bf419cae-814d-4918-9b8a-8c73ee15f2fc -i 22303980-180eea1d-ecc2-4728-98f3-6c2b63130289


  